name: Run Gradle check

on:
  push:
    branches:
      - main
      - releases/*
  pull-request:

jobs:
  gradle-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2.3.1
      with:
        distribution: 'temurin'
        java-version: '8'
    - uses: eskatos/gradle-command-action@v1
      name: gradle check
      with:
        arguments: check
